---
- hosts: me
  sudo: True
  tasks:
      - lvol:
          vg: "/dev/vgcloud"
          lv: "mango-lv1"
          size: "50"
      - filesystem:
         fstype: ext4
         dev: "/dev/vgcloud/mango-lv1"
      - file:
          path: "/object/mango-lv1"
          state: directory
      - mount:
          path: "/object/mango-lv1"
          src: "/dev/vgcloud/mango-lv1"
          fstype: ext4
          fstab: /webcontent/database/mountEntry.txt
          state: mounted

- hosts: mango
  tasks:
     - file:
         path: "/media/mango"
         state: directory
     - shell: "mount -t nfs -o nfsvers=3 192.168.0.113:/object/mango-lv1 /media/mango"